/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE
AO weight:1.0
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Traceback (most recent call last):
  File "test.py", line 222, in <module>
    main()
  File "test.py", line 88, in main
    image_extractor, model, optimizer = configure_model(args, trainset)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/utils/config_model.py", line 15, in configure_model
    model = ADE(dataset, args)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/ade.py", line 162, in __init__
    pretrained_weight = load_word_embeddings(args.emb_init, dset.attrs)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/word_embedding.py", line 10, in load_word_embeddings
    embeds = load_word2vec_embeddings(vocab)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/word_embedding.py", line 90, in load_word2vec_embeddings
    model = models.KeyedVectors.load_word2vec_format(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 1719, in load_word2vec_format
    return _load_word2vec_format(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 2048, in _load_word2vec_format
    with utils.open(fname, 'rb') as fin:
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 188, in open
    fobj = _shortcut_open(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 361, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './datasets//w2v/GoogleNews-vectors-negative300.bin'
/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE
AO weight:1.0
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Using all pairs
Dataset loaded
Train pairs: 29, Validation pairs: 22, Test Pairs: 67
Train images: 838, Validation images: 167, Test images: 1571
Traceback (most recent call last):
  File "test.py", line 222, in <module>
    main()
  File "test.py", line 88, in main
    image_extractor, model, optimizer = configure_model(args, trainset)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/utils/config_model.py", line 15, in configure_model
    model = ADE(dataset, args)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/ade.py", line 162, in __init__
    pretrained_weight = load_word_embeddings(args.emb_init, dset.attrs)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/word_embedding.py", line 10, in load_word_embeddings
    embeds = load_word2vec_embeddings(vocab)
  File "/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE/models/word_embedding.py", line 90, in load_word2vec_embeddings
    model = models.KeyedVectors.load_word2vec_format(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 1719, in load_word2vec_format
    return _load_word2vec_format(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 2048, in _load_word2vec_format
    with utils.open(fname, 'rb') as fin:
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 188, in open
    fobj = _shortcut_open(
  File "/home/gouidis/anaconda3/envs/ade/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 361, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './datasets//w2v/GoogleNews-vectors-negative300.bin'
/mnt/10TB/gouidis/Exps_Code_15142_CVPR24/ADE
Traceback (most recent call last):
  File "test.py", line 222, in <module>
    main()
  File "test.py", line 34, in main
    config = [os.path.join(logpath, _) for _ in os.listdir(logpath) if _.endswith('yml')][0]
FileNotFoundError: [Errno 2] No such file or directory: './logs/vaw_object'
